project_id = "lpqjjdgjjdozzfcclirb"

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-reservation-confirmation]
verify_jwt = false

[functions.send-reservation-reminder]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false
